version: '3'

services:
  metabase-app:
    image: metabase/metabase
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 3306
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: db-mysql
    depends_on:
      - db-mysql
    links:
      - db-mysql
  db-mysql:
    image: mysql:5
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: devops2022
      MYSQL_DATABASE: metabase
      MYSQL_USER: metabase
      MYSQL_PASSWORD: metabase